version: '3.3'

services:
  nginx:
    image: smackere:nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    networks:
      - network

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    image: img_mariadb:inc
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always
    networks:
      - network

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/smackere/data/mysqls
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/smackere/data/wordpress
      o: bind

networks:
  network:
    driver: bridge
