version: "3.3"

services:

  mariadb:
    container_name: mariadb
    image: smackere:mariadb
    build: ./requirements/mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - intra

  wordpress:
    container_name: wordpress
    image: smackere:wordpress
    build: ./requirements/wordpress
    environment:
      -WORDPRESS_DB_HOST: ${MYSQL_NAME} #mariadb
      -WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME} #wordpress
      -WORDPRESS_DB_USER: ${MYSQL_USER} #smackere
      -WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD} #Inception1@
    volumes:
    - wp:/var/www/html/wordpress
    networks:
      - intra
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: smackere:nginx
    build: ./requirements/nginx
    hostname: localhost
    volumes:
    - wp:/var/www/html/wordpress
    networks:
      - intra
    depends_on:
      - wordpress
    ports:
      - 443:443

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/data/db
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/data/wp

networks:
  intra:
    driver: bridge
